### ISSUE TITLE
Input string was not in the correct format

### ISSUE THREAD

**Issue by M1XT3NZ** [Vasar007/SteamWebApiLib#3]
**Describe the bug**
if you're trying to get the info of a package as you have shown it in an example it throws an "Input string was not in the correct format." error in the converters.cs 
also happens with FeaturedApps.

So just compiling your example with the GitHub project throws the "error"

**Comment by Vasar007** [comment]
Thanks for reporting! Sorry for the long wait, but GitHub does not send any notifications for the new issues in personal repositories :(

As for described error, I cannot reproduce it. I compiled current verion of this library and launched a [console project](https://github.com/Vasar007/SteamWebApiLib/tree/master/SteamWebApiLibConsoleApp) (because this one executes method from my example in [README file](https://github.com/Vasar007/SteamWebApiLib/blob/master/README.md)).

So, app was finished without any errors (at screenshot app waiting for pressing any key because of the line `Console.ReadLine();`):

![image](https://user-images.githubusercontent.com/21951872/71755080-23483f00-2e9a-11ea-91ad-05f7f22e4da2.png)

As far as I know, Steam have not released any breaking changes in their API at the current moment (January 2020). At least all available methods in this library work well.

Finally, I uses this library on everyday basis for my web-services of the [`ThingAppraiser` app](https://github.com/Vasar007/ThingAppraiser) and I have not encountered any errors in the entire time of use (from May 2019).

If you can provide more details about your issue (line in example which throws exception, stacktrace), I will try to investigate and fix it. Also if you attach info about your platform, system language and build cionfiguration it can helps to solve the issue too.

**Comment by Vasar007** [comment]
Well, if there are no more questions/suggestions, I closes the issue.
